### PR TITLE
Debugging

### PR DESCRIPTION
**Pull request by dzervas**
Add debugging configuration

Front end debugging:
image

Unit test debugging:
image

I also added the extension recommendations (and the .vscode folder in general)

### CODE REVIEW

**Comment by dzervas** [comment]
I'd like to be able to debug the WASM binary itself (set a breakpoint in Rust which is hit by a JS call) but it doesn't seem to be possible right now

**Review by jbcpollak — APPROVED** [review]
not that it matters but LGTM 😅

**Comment by av8ta** [comment]
Since most of us (all?) are on vscode then lgtm :)

**Comment by dzervas** [comment]
@jbcpollak it does! thanks for the review! <3

**Pull request merged**
